### PR TITLE
Add activity app

### PR DESCRIPTION
**Pull request by guyou**
BLE communications for tracking activity is too heavy in power consumption. Having an embedded application let offer a good alternative.

### CODE REVIEW

**Comment by sharandac** [comment]
For a better look, i have change the arc settings.

screen11

**Comment by guyou** [comment]
> For a better look, i have change the arc settings.
> 
> screen11

Nice!
I would work on improving the aspect now.
I'm also thinking about displaying the values (raw value or %) on top of the arc, and possibly with a horizontal layout.

**Comment by sharandac** [comment]
I think we can also leave out the "Steps:" and "Distance:" label so that there is more space. For example, for a horizontal layout :)

**Comment by guyou** [comment]
I also imagine add a refresh action in order to refresh display but also to try a BLE update notification.

**Pull request merged**
