### PR TITLE
fixes #77

### LINKED ISSUE #77: Using it with T-Watch 2019
Hello guys, 

Has any of you managed to get this firmware working properly on T-Watch 2019? 

I tried to `#define LILYGO_WATCH_2019_WITH_TOUCH` on config.h but yet the touchscreen doesnt seems to work. Main screen is displayed, looks like all other functionalities booted properly. But the screen cant recognize my touch.

Switching only this line of code above worked fine for lilygo examples library (https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/)

Any thoughts?

Thanks!

### PR DESCRIPTION
**Pull request by StarMX**
TTGO Watch 2019 touch fixes

### CODE REVIEW

**Comment by StarMX** [comment]
fixes

**Review by robouden — APPROVED** [review]

**Comment by datacute** [comment]
I've got changes ready for TTGO TWatch Library v1.4.0 which includes removing the rotation code from touch.cpp since `ttgo->getTouch( x, y )` (instead of `ttgo->touch->getPoint()`) processes the rotation.
Presumably without the custom code in My-TTGO-Watch, the rotation would work on TTGO Watch 2019 too - but I don't have one to test with.

**Comment by datacute** [comment]
I've pushed TTGO TWatch Library v1.4.0 support to experimental branch. Are you able to see if that works without needing to change the rotation code?
Unfortunately 1.4.0 creates a massive number of warnings, which are fixed in a later commit: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/commit/acad45608614bacf06082ac61874b39c77ce00c0

**Comment by StarMX** [comment]
not support TTGO TWatch Library@=1.4.0 I created the fix
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/pull/102

**Comment by StarMX** [comment]
wifictl.cpp line 326
#ifdef ENABLE_WEBSERVER error
#ifdef ENABLE_FTPSERVER

**Comment by datacute** [comment]
Thanks @StarMX 
I've updated experimental branch to use TTGO TWatch Library 1.4.1

**Pull request closed without merging**
