### PR TITLE
Change/Extend GPS Settings

### PR DESCRIPTION
**Pull request by dervomsee**
I modified/extended the GPS setting a little bit and included a logo.

In my opinion is was strange, that when calling the gpsctl_on, the gpsctl_config.autoon property is modified.
Because of this i created a new permission for apps, to turn GPS on/off. This permission is checked, when calling the gpsctl_on/gpsctl_off.

### CODE REVIEW

**Comment by sharandac** [comment]
I think gpsctl_on/off needs an explanation. gpsctl_on/off is supposed to switch gps on or off in general, so that it is immediately available again after a wakeup, or not. gpsctl_auto_on/off then switches gps on/off again depending on the autoon option in the configuration.
 As an example of how this works, you could use the Bluetooth switch in the status bar. If you switch off bluetooth there, it does not switch on again by itself after a wakeup.

**Comment by dervomsee** [comment]
The usecase in my mind is, the GPS is in general off, to save battery.
When i start the GPS app, it should turn on GPS. After closing the app, the GPS should be off again and should stay off.

The alternative would be, the app starts, receives no GPS data and the user has to turn on GPS manually. The app could notify the user in this situation.

What do you think is better?

**Comment by sharandac** [comment]
I would prefer to show a notice that GPS is turned off. If you consider that several apps can use GPS at the same time, it makes more sense.

By the way, have you seen Issue #240? Do you have these problems with the icons in the corners?

**Comment by dervomsee** [comment]
> I would prefer to show a notice that GPS is turned off. If you consider that several apps can use GPS at the same time, it makes more sense.

Ok, i will adapt the app. Another question regarding the app. Other apps are still open after pressing the on/off button. The GPS Status app gets closed and you are after returning from standby youre back on the maintile. How can i change this behavior?
I tried already this, but is does not help: https://github.com/sharandac/My-TTGO-Watch/blob/f8ec2742f95a3522733fd86b4bf990a41de2fc22/src/app/osmand/osmand_app_main.cpp#L226

> 
> By the way, have you seen Issue #240? Do you have these problems with the icons in the corners?

Yes, i have the problem too. I have to press the buttons in the edges 3-5 times to get apps closed, settings opened or stuff synced.. But as documented here, the versions are using the same HW: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library#-version-comparison-
I already searches in the datasheets for a calibration function or a sensitivity setting, but i found nothing.

**Comment by sharandac** [comment]
I hope this small example helps ...

```c
#include "gui/mainbar/mainbar.h"

static bool foobar_block_return_maintile = false;
void foobar_hibernate_cb( void );
void foobar_activate_cb( void );

/**
 * app setup
 */
void foobar_setup( uint32_t tile_num ) {
    ....
    /** register avtivate and hibernate callback function */
    mainbar_add_tile_activate_cb( tile_num, foobar_activate_cb );
    mainbar_add_tile_hibernate_cb( tile_num, foobar_hibernate_cb );
}

/**
 * automatic call when enter the app
 */
void foobar_activate_cb( void ) {
    /** save "block the maintile" value */
    foobar_block_return_maintile = display_get_block_return_maintile();
    /** overwrite "block the maintile" value */
    foobar_set_block_return_maintile( true );
}

/**
 * automatic call when leave the app
 */
void foobar_hibernate_cb( void ) {
    /** restore old "block the maintile value */
    display_set_block_return_maintile( foobar_block_return_maintile );
}
```

And for the touch ... take a look into hardware/touch.cpp line [155](https://github.com/sharandac/My-TTGO-Watch/blob/master/src/hardware/touch.cpp#L155). Here you can find some calibration multiplier

**Comment by dervomsee** [comment]
I reverted everything and the only remaining change is the preventing of the app from being closed.
You can close the PR and i will continue with my work in a new branch/PR.

Thanks and BR

**Pull request merged**
