### PR TITLE
alarm clock improvements

### PR DESCRIPTION
**Pull request by jakub-vesely**
feature: added days of week to alarm planning and a sound beep while an alarm occurs

refactoring: refactored way how are objects placed to tiles - offseting was replaced by placing to containers with a layout and padding. The padding is used as an extended clickable area. It lead to decreasing number of wrong clicking to an clickable object. It lead to unification of dialog layouts.

refactorig: rtc corresponding alarm functionality was fully moved to rtcctl
including its storing to a persistent file. Alarm occurrence corresponding functionality was moved to alarm_clock (alarm_clock_data was removed)

improvement: roller object in alarm_clock_main was adjusted to be
operable more smoothly (decreased height of line + addend 1 visible line)

### CODE REVIEW

**Comment by robouden** [comment]
Can we have also an hourly alarm? For day times and announcing the time? Would be useful for me. :)

**Comment by jakub-vesely** [comment]
> Can we have also an hourly alarm? For day times and announcing the time? Would be useful for me. :)

Hi Robouden, to be honest, I do not understand what exactly do you mean. May I ask you to describe your use case a little bit more.  
Do you mean to to beep every whole hour (1:00, 2:00,...) as was used to for a first digital watch, or do you want to be able to set alarm to particular minute that will be raised every hour? 

What do you expect that will happen in the alarm time? Just short beep, to display alarm_in_progress tile with necessity to close (as same as for common alarm), or do you expect that the watch says "its five o'clock".

Best regards, Jakub

**Comment by robouden** [comment]
For me, it would be very useful to have te clock announce the time every hour to keep track easy for meetings. The watch says "its five o'clock". And then even 5 minutes before the hour, so I can prepare a bit. :)

**Comment by jakub-vesely** [comment]
I'm afraid that your use case is really specific and actually a kind of workaround. The proposed solution do not solve issue when the meeting starts at e.g. 10:30.   What you actually wants is to be notified before meetings. It would be better to solve this issue instead. The best solution would be to implement a calendar with imported appointments. 

I plan to do one more improvement iteration to alarm clock app - to allow to set more alarms at once (up to 3 maybe more if will be feasible in the gui) to be possible to set different alarms to different days. Maybe it could solve your issue partially. But still it will be a workaround. You actually needs a calendar with appointments.

**Comment by robouden** [comment]
I understand your thinking. But I personally would like the option to set an alarm every hour (better a few minutes before) I have now y tablet setup like that and works fine for me. But nicer if the phone could do that too. !!!

**Comment by aleksandr23uam23** [comment]
Good afternoon. Thank you for developing this project hours. I really like this project! I would like to ask you to add modes on schedule to the alarm clock, I work on the chart "Day, Night 48" and I really want to implement this schedule. So that in the alarm clock it was possible to set the triggering, for example: "day" **: * ", and every 4 days he was repeated;" On the night "**: **, and every 4 days he was repeated;" From night "*": * ", and every 4 days

**Comment by aleksandr23uam23** [comment]
Good afternoon. Thank you for developing this project hours. I really like this project! I would like to ask you to add modes on schedule to the alarm clock, I work on the chart "Day, Night 48" and I really want to implement this schedule. To the alarm clock it was possible to set the triggering, for example: "Day" **:**, and every 4 days he repeated; "On the night" **: **, and every 4 days he repeated; "From night" **: **, and every 4 days he repeated; Output **: **, and every 4 days he repeated. Where **: ** - the ability to set the time. Thank you!

**Pull request merged**
