### PR TITLE
Add sound settings tile

### PR DESCRIPTION
**Pull request by paulstueber**
**Summary**
Global sound settings can be configured via a configuration menu/tile.

**Details**
Sound can be disabled and volume can be set (globally)
Sound property (sound.c) was extended to also store a volume attribute. Everything is stored on the SPIFFS.

### CODE REVIEW

**Comment by NorthernDIY** [comment]
I haven't looked at the code for this yet, but if you can, make it disable the pmu output for the i2s DAC when sound is disabled.  It saves 1.2mA or so, which is small but still worth saving imo.

**Comment by NorthernDIY** [comment]
Also, great work! I'm looking forward to adding some bleeps to go along with the buzzing.

**Review by sharandac — APPROVED** [review]
Also, great work!

can you implement standby and wakeup in the next version? we could save some more power.

**Comment by paulstueber** [comment]
Hi thank you @NorthernDIY & @sharandac for your comments. I'll add the suggested power saving changes in the next PR

**Comment by robouden** [comment]
Are you thinking of the option for example announce to the time in combination with the alarm clock?

**Pull request merged**
