### PR TITLE
User expressions to control the behavior of the watchface

### PR DESCRIPTION
**Pull request by guyou**
Let the user define the behavior of the watchface with expression based on internal values.

Examples: 

* use math expression for display label: `{..."type":"expr","expr":"steps()/2"...}` to display half step value
* use bool expression to display image: `{..."enable":"bluetooth_messages()>0"...` to display an image when there are messages
* use math expression to rotate image: `{..."rotation":"0 + ( ( tm_hour * 364 ) / 24)"...}` to display hour or `{..."rotation":"10 + ( battery_percent * 170 / 100)"...}` to display a gauge for battery
* ...

Main ideas:
* offer full power/expressivity to watchface designer
* add more dynamic controls (enable a part based on context)

### CODE REVIEW

**Comment by guyou** [comment]
Here is a first major step: expressions are available:
- for a label value
- to control display of watchface's part, due to the `enable` flag.

For example, to display GPS symbol when GPS is enabled.
```
    {
      "enable": "gps > 0",
      "type": "text",
      "label": "\uF124",
      "font": "Montserrat",
      "font_color": "#6c680d",
      "align": "center",
      "font_size": 16,
      "x_offset": 206,
      "y_offset": 20,
      "x_size": 24,
      "y_size": 20
    },
```

@sharandac and @reality52 what do you think about merging this stage into `experimental` branch? It will allow to start using it to rewrite some watchfaces in order to introduce dynamic changes.

but before that, it needs some more tests.

**Comment by sharandac** [comment]
@guyou and @reality52 I think a separate branch is better for testing until all basic functions work as expected.

**Comment by guyou** [comment]
@sharandac what is the goal of saving the [watchface_theme_config](https://github.com/sharandac/My-TTGO-Watch/blob/028e2456f97f3ccb9c615c5e00e49ad69be79a00/src/gui/mainbar/setup_tile/watchface/watchface_tile.cpp#L555)?
I feel it not so required.

Saving the config implies to be able to serialize all part of the config. But there is no easy way to serialize a *compiled expression* (tinyexpr). So, to be able to save an expr, we have to save its raw form, as string. As we can imagine many many config's parameters as expressions, we have to provision lot of static strings, just to save them back, before reading them back.
Without having to save the config, we can avoid storing the raw expression and provisioning all of these static strings.

Can I suppress saving the config?

**Comment by sharandac** [comment]
@guyou Sure, do that. That was actually meant as a check to clean up the JSON from non-usable expressions.

**Pull request merged**
