### PR TITLE
Stopwatch and Analog Watchface

### PR DESCRIPTION
**Pull request by Neuroplant**
Added an Analog Watchface replacing "Note" Tile
Added Hour and 1/100s to Stopwatch

### CODE REVIEW

**Comment by sim1988son** [comment]
Analog Watchface nie aktualizue czasu do timezone

**Comment by Neuroplant** [comment]
FindPhone App completed
Works in both directions (Search for Phone, Search for Watch)

**Comment by datacute** [comment]
Are you able to split this into two pull requests? I'd like to be able to consider the FindPhone feature independently.

**Comment by Neuroplant** [comment]
Hallo
I will try to do this, as soon as I figure out how.
I am looking for a way to provide the apps and watchfaces separately.

Gruß
Neuroplant

Stephen Denne <notifications@github.com> schrieb am Sa., 21. Nov. 2020,
06:12:

**Comment by Neuroplant** [comment]
@datacute 
how about this?
[https://github.com/Neuroplant/My-TTGO-Watch_FindPhoneApp](url)

**Comment by sharandac** [comment]
Thanks for your pull-request. Can you split this one into three? (analog watchface, walking-app and findphone-app) The walking-app uses over 1MB of additional flash, which is a lot. 
The analog watchface should be adjusted, so that it fits into the tile correctly, it sticks out into the status bar.

**Pull request merged**
