### PR TITLE
Ble activity support

### LINKED ISSUE #135: Extend Gadgetbridge Support
Since we're pretending to be an Espruino Bangle.js ... the message formats that we can support are documented here:
https://www.espruino.com/Gadgetbridge
There are a few that are not yet supported that could be added:
1. "find" - we could turn on the screen, show a page that allows clicking to say you've found the watch, vibrate and make noise - depending on various existing config settings (e.g. don't make noise if sound is turned off, don't vibrate if the motor is turned off).
2. "alarm" - we could support configuring the alarm
3. "weather" (I haven't seen my android phone send this to my watch - does it require another phone app?) - we could supply weather details to show.

### PR DESCRIPTION
**Pull request by guyou**
Add support for notifying activity (stepcounter) via BLE.

* [x] notify data
* [x] optimize notification frequency (timer / value threshold)
* [x] support request for realtime step counting message from Gadgetbridge

Fixes #135

### CODE REVIEW

**Comment by guyou** [comment]
I'm quite satisfied with such state of work.

@sharandac what's your opinion?

One missing part: should we increase the notification rate and how? In realtime mode, GadgetBridge requires notification every 5 seconds.

**Comment by guyou** [comment]
I think it is a significantly stable change to share it.

**Comment by guyou** [comment]
@sharandac please, refresh the branch, as I forgot documentation.

**Comment by sharandac** [comment]
@guyou you mean revert?

**Comment by guyou** [comment]
> @guyou you mean revert?

I've updated the branch. So You just have to pull and merge.

**Pull request merged**
