### PR TITLE
Create release.yml

### PR DESCRIPTION
**Pull request by guyou**
Let Github creates the release assets when tags are pushed.

Many goals:

- no more time spent on it
- no more storage of generated binaries inside the Git repo (it is bad ;-)) but store them into Github's release system

PS: storing rolling binaries (like the firmware) is a bad practice because all versions will be kept in the Git repo, making it growing faster and faster.

### CODE REVIEW

**Comment by guyou** [comment]
Hi @sharandac, how is generated the file ttgo-t-watch2020_v1.version.json?

**Comment by guyou** [comment]
Example of release with both firmware and compressed firmware: https://github.com/guyou/My-TTGO-Watch/releases/tag/v1.0-guyou-4

**Comment by sharandac** [comment]
@guyou  The .json is generated with a simple shell script which collects all the important data like branch name, version from config.h and so on. I've been thinking about not publishing any binary files for a while now and only releasing a new one every 2-3 months.

**Comment by guyou** [comment]
> @guyou The .json is generated with a simple shell script which collects all the important data like branch name, version from config.h and so on. I've been thinking about not publishing any binary files for a while now and only releasing a new one every 2-3 months.

I don't know what system consume this JSON file. Perhaps can you store the script in the tree (`bin/` or `tools/`). The consumer tool can certainly be adapted to consume this file from Github's release system. Generally, the most complex part is to find the latest release. But Github has [a link for that](https://docs.github.com/en/rest/reference/repos#get-the-latest-release).

**Comment by sharandac** [comment]
the .json holds all the information for the updater. the structure is simple. here is my bash script to generate the all the files depends on the current branch.

```
{
    "version":"2021020502",
    "host":"http://www.neo-guerillaz.de",
    "size":"4610336",
    "file":"ttgo-t-watch2020_v1.experimental.ino.bin",
    "gzipfile":"ttgo-t-watch2020_v1.experimental.ino.bin.gz",
    "md5":"84ebc0efce3b386cbfe813cf8f026974",
    "comment":""
}
```

```bash
#!/bin/bash
#
# build and deplay tool
#
clear

# build firmware
platformio run --target clean
platformio run

# get the right path and branchname
path=$(ls -d .pio/build/ | cut -d'/' -f 2)
branch=$(git rev-parse --abbrev-ref HEAD)
# get firmware version from config.h
firmwareversion=$(cat src/config.h | grep __FIRMWARE__ | tr -s " " | cut -d' ' -f4 | cut -d'"' -f2)

echo "path: $path"
echo "version: $firmwareversion"


# build .json depend on brach name
if [ "$branch" == "experimental" ]; then
    cp .pio/$path/ttgo-t-watch/firmware.bin ttgo-t-watch2020_v1.experimental.ino.bin
    md5=$(md5sum ttgo-t-watch2020_v1.experimental.ino.bin | cut -d ' ' -f 1)
    size=$(ls -la *experimental.ino.bin | cut -d' ' -f5)
    gzip -k ttgo-t-watch2020_v1.experimental.ino.bin
    echo "{\"version\":\"$firmwareversion\",\"host\":\"http://www.neo-guerillaz.de\",\"size\":\"$size\",\"file\":\"ttgo-t-watch2020_v1.experimental.ino.bin\",\"gzipfile\":\"ttgo-t-watch2020_v1.experimental.ino.bin.gz\",\"md5\":\"$md5\",\"comment\":\"$1\"}" > ttgo-t-watch2020_v1.experimental.version.json
    echo "File to send:"
    echo "-------------------------------"
    echo "Version: $firmwareversion"
    echo "size: $size"
    echo "md5: $md5"
    ls | grep ttgo-t-watch2020_v1.experimental
    echo "-------------------------------"
    echo "copy firmware to Server"
    scp ttgo-t-watch2020_v1.experimental* root@192.168.22.1:/var/www/
    echo "done."
    rm *.experimental*
fi

if [ "$branch" == "master" ]; then
    cp .pio/$path/ttgo-t-watch/firmware.bin ttgo-t-watch2020_v1.ino.bin
    md5=$(md5sum ttgo-t-watch2020_v1.ino.bin | cut -d ' ' -f 1)
    size=$(ls -la *.ino.bin | cut -d' ' -f5)
    rm ttgo-t-watch2020_v1.ino.bin.gz
    gzip -k ttgo-t-watch2020_v1.ino.bin
    echo "{\"version\":\"$firmwareversion\",\"host\":\"http://www.neo-guerillaz.de\",\"size\":\"$size\",\"file\":\"ttgo-t-watch2020_v1.ino.bin\",\"gzipfile\":\"ttgo-t-watch2020_v1.ino.bin.gz\",\"md5\":\"$md5\",\"comment\":\"$1\"}" > ttgo-t-watch2020_v1.version.json
    echo "File to send:"
    echo "-------------------------------"
    echo "Version: $firmwareversion"
    echo "size: $size"
    echo "md5: $md5"
    ls | grep ttgo-t-watch2020_v1
    echo "-------------------------------"
    echo "copy firmware to Server"
    scp ttgo-t-watch2020_v1* root@192.168.22.1:/var/www/
    echo "done."
fi
```

**Comment by guyou** [comment]
OK, thanks.

So I realize I have a question: what is your workflow for now and/or near future? Do you plan to host only two releases (experimental and stable) or many versions to let users return to previous versions if new one fails?

In first option, we can certainly revise the master related file name to replace v1 by `stable` or something like that.
In second option, we can reuse the Github workflow I'm experimenting and start tagging releases.

There is also an other median option: propose many versions available to user, but use timestamp instead of tag, and release each time a commit is pushed on master branch.

Does the updater can use files from Github? Or should it be based on your website?

**Comment by sharandac** [comment]
Currently I create the two versions with the script when I have made a commit. I would like to keep the v1, as the V2 and V3 hardware versions of the watch also exist. A separate file would have to be created later for each version. I really only wanted to host two versions, master and experimental.

I have tried to get the files from github, but unfortunately there is not enough RAM to use SSL/TLS.

I'll have to think about it again tomorrow, it's very late here at the moment.

**Comment by guyou** [comment]
> Currently I create the two versions with the script when I have made a commit. I would like to keep the v1, as the V2 and V3 hardware versions of the watch also exist. A separate file would have to be created later for each version. I really only wanted to host two versions, master and experimental.
> 

OK. I will revise my contribution to focus on only two branches and two versions.

While GitHub is not necessarily a solution, I can imagine two options:

1. the script directly deploys on your website (I would suggest to create a dedicated SSH key, use an unpriviledged account, some SSH filtering in the authorized_keys, and anything else ruggifying this input)
2. your webserver act like a HTTP->HTTPS proxy: any request to a local URL triggers a download from Github by webserver itself. This way, the webserver is responsible of th SSL part.

A derived option is a deadly simple cron, checking GitHub every minutes and downloading new release of both versions.
A quite trivial webhook can also be created: once the release is published on GitHub, the GitHub action triggers the webhook which will, in return, download the new files.

**Comment by guyou** [comment]
I revisited the workflows.

The last piece of code: upload the files to your own server, if wished.

**Pull request merged**
