### PR TITLE
Added background image selection

### PR DESCRIPTION
**Pull request by ssspeq**
Added selection of background image to display settings tile

### CODE REVIEW

**Comment by sharandac** [comment]
some hints:

- **set_background_image** in **gui.cpp/.h** does not correspond to the correct naming. **gui_set_background_image** would be better ...

- it is not a good idea to call a gui function from **display.cpp**. display means hardware and gui creates the content, like for example a background image

- it's a bit tricky to find the place where the background is set at boot, i think it would be better in gui.cpp. but it's ok to save it in the display settings.

and one for the future, I'm currently in the experimental branch, reworking the software to include a better separation between **gui** and **drivers**, allowing for better porting in the future. It would be great if you could commit there.

**Comment by ssspeq** [comment]
I will fix it according to your suggestions and try again. :-)

**Comment by sharandac** [comment]
Yeah!

**Comment by ssspeq** [comment]
Is this better? There is a call to display_get_background_image from gui.cpp to get the correct background image from settings at boot. Not sure how to avoid that.

**Comment by sharandac** [comment]
the only way to avoid that is a new a new config file like gui.json. we save that for later mission :)

**Pull request merged**
