### PR TITLE
Activity horiz layout

### PR DESCRIPTION
**Pull request by guyou**
I tried an horizontal layout for Tracker Activity

@sharandac feel free to discuss before merge. It's some sort of Work In Progress and many detail can be discussed.

### CODE REVIEW

**Comment by sharandac** [comment]
It looks very good! But i think a unit label for the step counter is more practical and it would look better if we put the two arc more in the middle.

screen

**Comment by guyou** [comment]
> It looks very good! But i think a unit label for the step counter is more practical and it would look better if we put the two arc more in the middle.
> 

Perhaps should we display raw values (steps + distance) below the arcs.

On my side, I really like the idea to use the **big** font to display raw values: this application let the user check his activity, so values should be easy to read. So, keeping both values (steps + distance) on the same line would be hard.
Any idea?

**Comment by sharandac** [comment]
It is a pity that others do not share their code ...

[https://twitter.com/sim1988son/status/1342241755006164992/photo/1](https://twitter.com/sim1988son/status/1342241755006164992/photo/1)

**Comment by guyou** [comment]
> It is a pity that others do not share their code ...
> 
> https://twitter.com/sim1988son/status/1341031160110039040

Here is his Github account: https://github.com/sim1988son
But I didn't find the code.

Nevertheless, a good idea for design.

**Comment by sharandac** [comment]
That's what I meant. But I do like the layout.

**Pull request merged**
