### PR TITLE
Move BLE message formatting into blectl module

### PR DESCRIPTION
**Pull request by guyou**

### CODE REVIEW

**Comment by guyou** [comment]
@sharandac while looking at this part of code, I realize something is'nt clear enought to me in the design.

Previously to this patch, BLE message was formatted and sent from pmu.cpp while the same information is updated and notified from blectl.cpp (blectl_update_battery) mostly because BLE Characteristic are internal to blectl.
Having the same information processed at two separated layers is not easy to understand. So I decided the present patch, grouping all into blectl.
But now, I realized that this is not an elegant design: for consistency, following such design we would have to move all BLE messages formatting from apps to blectl. Weird.

A most clean design would be to have a new module (blebatt / blebattctl?) responsible of reacting to PMUCTL_* callbacks and sending BLE message.
Note: the same should/would be done in the step counter BLE notification (work in progress: https://github.com/sharandac/My-TTGO-Watch/pull/191)

What's your opinion?

**Comment by sharandac** [comment]
That is a good point. Initially, blectl was only meant for sending BLE messages for gadgetbridge. And then other programmers came along and added that :-) it just grew like that.
Splitting it into separate blebatctl and blestepclt sounds logical. But I don't have time to work on it for the next 2-4 weeks :(

**Comment by guyou** [comment]
> That is a good point. Initially, blectl was only meant for sending BLE messages for gadgetbridge. And then other programmers came along and added that :-) it just grew like that.
> Splitting it into separate blebatctl and blestepclt sounds logical. But I don't have time to work on it for the next 2-4 weeks :(

OK, thanks for feedback. No matter for the time, I plan to do this in the next days. I understand you won't be available for review for the next weeks. I will work on my side.

I already have many changes in many direction around this topic. I also have changes to experiment reducing power consumption. Currently, with Bluetooth activated, the watch works less than half a day. I hope to find optimizations and settings to have it working for a full day.

**Comment by guyou** [comment]
Obsoleted by commit dcc615a0b05e328600b83bf325e7a51ea15761ef

**Pull request closed without merging**
